name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

env:
  DOCKER_USR: ${{ secrets.DOCKER_USR }}

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Tree
        uses: hasheddan/action-tests@master
      - name: Build xpkg
        uses: crossplane-contrib/xpkg-action@master
        with:
          command: build
          type: configuration
          path: nested/nested.yaml
          destination: --name=xpkg-action-test
