name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      channel:
        description: release channel
        required: true
        default: stable
      version:
        description: release version
        required: true
        default: current

env:
  DOCKER_USR: ${{ secrets.DOCKER_USR }}

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to Docker
        uses: docker/login-action@v1
        if: env.DOCKER_USR != ''
        with:
          registry: registry.upbound.io
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PSW }}
      - name: Set tag
        run: echo "::set-output name=VERSION_TAG::$(git describe --dirty --always --tags | sed 's/-/./2' | sed 's/-/./2' )"
        id: tagger
      - name: Build
        uses: crossplane-contrib/xpkg-action@master
        with:
          channel: ${{ github.event.inputs.channel }}
          version: ${{ github.event.inputs.version }}
          command: build configuration -f nested --name=xpkg-action-test
      - name: Push
        uses: crossplane-contrib/xpkg-action@master
        with:
          command: push configuration -f nested/xpkg-action-test.xpkg registry.upbound.io/crossplane-test/xpkg-action-test:${{ steps.tagger.outputs.VERSION_TAG }}
      - name: Push Latest
        uses: crossplane-contrib/xpkg-action@master
        with:
          command: push configuration -f nested/xpkg-action-test.xpkg registry.upbound.io/crossplane-test/xpkg-action-test
  test2:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to Docker
        uses: docker/login-action@v1
        if: env.DOCKER_USR != ''
        with:
          registry: registry.upbound.io
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PSW }}
      - name: Set tag
        run: echo "::set-output name=VERSION_TAG::$(git describe --dirty --always --tags | sed 's/-/./2' | sed 's/-/./2' )"
        id: tagger
      - name: Build
        uses: crossplane-contrib/xpkg-action@master
        with:
          command: build configuration -f nested --name=xpkg-action-test
      - name: Push
        uses: crossplane-contrib/xpkg-action@master
        with:
          command: push configuration -f nested/xpkg-action-test.xpkg registry.upbound.io/crossplane-test/xpkg-action-test-2:${{ steps.tagger.outputs.VERSION_TAG }}
      - name: Push Latest
        uses: crossplane-contrib/xpkg-action@master
        with:
          command: push configuration -f nested/xpkg-action-test.xpkg registry.upbound.io/crossplane-test/xpkg-action-test-2
